### ISSUE TITLE
Any update on fixing video downloads?

### ISSUE THREAD

**Issue by ehaase23** [Motyldrogi/fansly-downloader#28]
I realize there are several threads on this, but I don't see a solution.  Photos download as .png files, but videos don't download at all.  I have deselected "auto" quality and tried other suggestions from the threads.  Nothing works.  Would love to see an update.  Thanks.

**Comment by RalkeyOfficial** [comment]
Its not going to be fixed anytime soon.
Fansly changed the way videos are displayed, which makes it impossible to download it from an extension, since it will also need to do some automated video editing.

I recommend just switching to https://github.com/Avnsx/fansly-downloader

**Comment by god43** [comment]
yeah that guys stuff doesn't work either, then then he just blocks you from commenting when you point out that it doesn't work.

**Comment by RalkeyOfficial** [comment]
> yeah that guys stuff doesn't work either, then then he just blocks you from commenting when you point out that it doesn't work.

We're aware it doesnt work and im working alongside Avnsx to fix it. Doent help that he is also on vacation with only a phone alongside him

**Comment by DeltaBoss** [comment]
fansly just updated smth on their side and v2.0.6 seems to magically be working again for new videos, although not for videos in the "broken" timeframe

**Comment by IBananaShake** [comment]
Any news regarding video downloads?

**Comment by buildog** [comment]
> Any news regarding video downloads?

Try www.replaaay.com

**Comment by IBananaShake** [comment]
It doesn't let me download stuff that was sendt in DMs

**Comment by RalkeyOfficial** [comment]
> It doesn't let me download stuff that was sendt in DMs

What, for this project? Or for Avnsx's Fansly Downloader

**Comment by IndiePay** [comment]
This is not update.
Try https://github.com/IndiePay/FanslyDownloader still work.

**Comment by IBananaShake** [comment]
> > It doesn't let me download stuff that was sendt in DMs
> 
> What, for this project? Or for Avnsx's Fansly Downloader

There is no download button on Fansly for anything anymore, even when I try to redownload the extension

**Comment by IndiePay** [comment]
> > > It doesn't let me download stuff that was sendt in DMs
> > 
> > 
> > What, for this project? Or for Avnsx's Fansly Downloader
> 
> There is no download button on Fansly for anything anymore, even when I try to redownload the extension

Are you install it in the chrome?You can follow this steps to manually install it: https://fanslydownloader.com/how-to-manually-install-fansly-downloader/

**Comment by Zero3K** [comment]
> This is not update. Try https://github.com/IndiePay/FanslyDownloader still work.

That one costs money to be able to use all of its features.

**Comment by Zero3K** [comment]
content.js:182 Uncaught 
TypeError: Cannot read properties of undefined (reading 'split')
    at content.js:182:67
    at Array.forEach (<anonymous>)
    at HTMLDivElement.onDownloadClickFeed (content.js:170:17)

**Comment by ultracoolboy** [comment]
there still no way to download videos xd
